/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'PyTorch Deep Dive',
          link: {type: 'doc', id: 'guides/pytorch-deep-dive/README'},
          items: [
            {
              type: 'category',
              label: 'Phase 1: Tensors and the Storage Model',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/stride-explorer/README', label: 'Stride explorer'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/view-vs-copy-detective/README', label: 'View vs copy detective'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/manual-indexing/README', label: 'Manual indexing'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/dtype-precision-study/README', label: 'dtype precision study'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/broadcasting-bug-hunt/README', label: 'Broadcasting bug hunt'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 2: Autograd, Inside Out',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/micrograd-in-pytorch-style/README', label: 'Micrograd in PyTorch style'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/manual-backprop/README', label: 'Manual backprop'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/custom-autograd-function/README', label: 'Custom autograd.Function'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/straight-through-estimator/README', label: 'Straight-through estimator'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/gradient-checkpointing/README', label: 'Gradient checkpointing'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/double-backward/README', label: 'Double backward'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 3: nn.Module, Optimizers, and the Training Loop',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/module-introspection/README', label: 'Module introspection'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/hook-based-feature-extractor/README', label: 'Hook-based feature extractor'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/custom-optimizer/README', label: 'Custom optimizer'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/implement-adamw-from-scratch/README', label: 'Implement AdamW from scratch'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/state-dict-surgery/README', label: 'State dict surgery'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/reproducible-training/README', label: 'Reproducible training'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 4: Data Loading and Input Pipelines',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/naive-vs-optimized-loader/README', label: 'Naive vs optimized loader'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/custom-collate/README', label: 'Custom collate'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/weighted-sampler/README', label: 'Weighted sampler'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/streaming-webdataset/README', label: 'Streaming WebDataset'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/memory-mapped-tokens/README', label: 'Memory-mapped tokens'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/profile-and-fix/README', label: 'Profile and fix'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 5: Performance',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/profile-a-training-step/README', label: 'Profile a training step'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/amp-speedup-study/README', label: 'AMP speedup study'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/torch-compile-test/README', label: 'torch.compile test'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/memory-breakdown/README', label: 'Memory breakdown'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/gradient-accumulation/README', label: 'Gradient accumulation'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/bottleneck-fix/README', label: 'Bottleneck fix'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 6: Custom Kernels',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/cpp-extension-for-elementwise-add/README', label: 'C++ extension for elementwise add'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/triton-softmax/README', label: 'Triton softmax'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/triton-matmul/README', label: 'Triton matmul'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/fused-mlp/README', label: 'Fused MLP'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/mini-flashattention/README', label: 'Mini FlashAttention'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/custom-op-registration/README', label: 'Custom op registration'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 7: Distributed Training',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/two-gpu-ddp/README', label: 'Two-GPU DDP'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/implement-gradient-allreduce/README', label: 'Implement gradient AllReduce'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/fsdp-a-transformer/README', label: 'FSDP a transformer'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/tensor-parallel-attention/README', label: 'Tensor parallel attention'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/debug-a-hang/README', label: 'Debug a hang'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/multi-node-setup/README', label: 'Multi-node setup'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 8: Deployment',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/export-to-onnx/README', label: 'Export to ONNX'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/mobile-deployment/README', label: 'Mobile deployment'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/dynamic-quantization/README', label: 'Dynamic quantization'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/static-quantization-ptq/README', label: 'Static quantization (PTQ)'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/build-a-triton-server/README', label: 'Build a Triton server'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/latency-profiling/README', label: 'Latency profiling'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 9: Debugging Hard Problems',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/nan-forensics/README', label: 'NaN forensics'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/memory-leak-hunt/README', label: 'Memory leak hunt'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/determinism-audit/README', label: 'Determinism audit'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/hang-diagnosis/README', label: 'Hang diagnosis'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/eager-vs-compile-diff/README', label: 'Eager vs compile diff'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 10: Reading the PyTorch Source',
              items: [
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/trace-one-op-end-to-end/README', label: 'Trace one op end to end'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/read-native-functions-yaml/README', label: 'Read native_functions.yaml'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/build-pytorch-from-source/README', label: 'Build PyTorch from source'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/patch-and-rebuild/README', label: 'Patch and rebuild'},
                {type: 'doc', id: 'guides/pytorch-deep-dive/projects/fix-a-good-first-issue/README', label: 'Fix a "good first issue"'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'LLM',
          link: {type: 'doc', id: 'guides/llm/README'},
          items: [
            {
              type: 'category',
              label: 'Phase 1: Tokenization and Embeddings',
              items: [
                {type: 'doc', id: 'guides/llm/projects/train-a-bpe-from-scratch/README', label: 'Train a BPE from scratch'},
                {type: 'doc', id: 'guides/llm/projects/tokenizer-compression-study/README', label: 'Tokenizer compression study'},
                {type: 'doc', id: 'guides/llm/projects/numeral-tokenization-audit/README', label: 'Numeral tokenization audit'},
                {type: 'doc', id: 'guides/llm/projects/chat-template-debugger/README', label: 'Chat-template debugger'},
                {type: 'doc', id: 'guides/llm/projects/custom-vocab-extension/README', label: 'Custom vocab extension'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 2: The Transformer Architecture',
              items: [
                {type: 'doc', id: 'guides/llm/projects/single-attention-head/README', label: 'Single attention head'},
                {type: 'doc', id: 'guides/llm/projects/multi-head-attention/README', label: 'Multi-head attention'},
                {type: 'doc', id: 'guides/llm/projects/nanogpt-reproduction/README', label: 'nanoGPT reproduction'},
                {type: 'doc', id: 'guides/llm/projects/pre-norm-vs-post-norm/README', label: 'Pre-norm vs post-norm'},
                {type: 'doc', id: 'guides/llm/projects/rope-from-scratch/README', label: 'RoPE from scratch'},
                {type: 'doc', id: 'guides/llm/projects/gqa-ablation/README', label: 'GQA ablation'},
                {type: 'doc', id: 'guides/llm/projects/mini-moe/README', label: 'Mini-MoE'},
                {type: 'doc', id: 'guides/llm/projects/long-context-extension/README', label: 'Long-context extension'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 3: Pretraining — Data, Objectives, and the Loss Curve',
              items: [
                {type: 'doc', id: 'guides/llm/projects/train-a-10m-parameter-lm/README', label: 'Train a 10M-parameter LM'},
                {type: 'doc', id: 'guides/llm/projects/train-a-100m-parameter-lm/README', label: 'Train a 100M-parameter LM'},
                {type: 'doc', id: 'guides/llm/projects/dedup-ablation/README', label: 'Dedup ablation'},
                {type: 'doc', id: 'guides/llm/projects/quality-filter-ablation/README', label: 'Quality-filter ablation'},
                {type: 'doc', id: 'guides/llm/projects/lr-schedule-sweep/README', label: 'LR schedule sweep'},
                {type: 'doc', id: 'guides/llm/projects/loss-spike-forensics/README', label: 'Loss-spike forensics'},
                {type: 'doc', id: 'guides/llm/projects/continued-pretraining/README', label: 'Continued pretraining'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 4: Scaling Laws and Training Infrastructure',
              items: [
                {type: 'doc', id: 'guides/llm/projects/reproduce-a-mini-chinchilla-plot/README', label: 'Reproduce a mini-Chinchilla plot'},
                {type: 'doc', id: 'guides/llm/projects/compute-calculator/README', label: 'Compute calculator'},
                {type: 'doc', id: 'guides/llm/projects/fsdp-from-scratch-toy/README', label: 'FSDP from scratch (toy)'},
                {type: 'doc', id: 'guides/llm/projects/activation-checkpointing-study/README', label: 'Activation checkpointing study'},
                {type: 'doc', id: 'guides/llm/projects/bf16-vs-fp8-ablation/README', label: 'BF16 vs FP8 ablation'},
                {type: 'doc', id: 'guides/llm/projects/loss-spike-recovery-drill/README', label: 'Loss-spike recovery drill'},
                {type: 'doc', id: 'guides/llm/projects/multi-node-training/README', label: 'Multi-node training'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 5: Post-training — SFT, RLHF, DPO, GRPO, RLVR',
              items: [
                {type: 'doc', id: 'guides/llm/projects/sft-a-1b-base-model/README', label: 'SFT a 1B base model'},
                {type: 'doc', id: 'guides/llm/projects/loss-masking-bug-hunt/README', label: 'Loss-masking bug hunt'},
                {type: 'doc', id: 'guides/llm/projects/lora-qlora/README', label: 'LoRA / QLoRA'},
                {type: 'doc', id: 'guides/llm/projects/train-a-reward-model/README', label: 'Train a reward model'},
                {type: 'doc', id: 'guides/llm/projects/ppo-rlhf-loop/README', label: 'PPO RLHF loop'},
                {type: 'doc', id: 'guides/llm/projects/dpo-from-scratch/README', label: 'DPO from scratch'},
                {type: 'doc', id: 'guides/llm/projects/grpo-on-a-math-task/README', label: 'GRPO on a math task'},
                {type: 'doc', id: 'guides/llm/projects/reward-hacking-forensics/README', label: 'Reward-hacking forensics'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 6: Reasoning and Inference-Time Compute',
              items: [
                {type: 'doc', id: 'guides/llm/projects/cot-vs-direct-on-gsm8k/README', label: 'CoT vs. direct on GSM8K'},
                {type: 'doc', id: 'guides/llm/projects/self-consistency-sweep/README', label: 'Self-consistency sweep'},
                {type: 'doc', id: 'guides/llm/projects/best-of-n-with-a-reward-model/README', label: 'Best-of-N with a reward model'},
                {type: 'doc', id: 'guides/llm/projects/process-reward-model/README', label: 'Process reward model'},
                {type: 'doc', id: 'guides/llm/projects/tree-of-thoughts-on-a-logic-puzzle/README', label: 'Tree-of-Thoughts on a logic puzzle'},
                {type: 'doc', id: 'guides/llm/projects/mini-r1-recipe/README', label: 'Mini R1 recipe'},
                {type: 'doc', id: 'guides/llm/projects/length-budget-controller/README', label: 'Length-budget controller'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 7: Retrieval, Tools, and Agents',
              items: [
                {type: 'doc', id: 'guides/llm/projects/minimal-rag/README', label: 'Minimal RAG'},
                {type: 'doc', id: 'guides/llm/projects/chunking-ablation/README', label: 'Chunking ablation'},
                {type: 'doc', id: 'guides/llm/projects/reranker-effect/README', label: 'Reranker effect'},
                {type: 'doc', id: 'guides/llm/projects/hybrid-retrieval/README', label: 'Hybrid retrieval'},
                {type: 'doc', id: 'guides/llm/projects/tool-using-chatbot/README', label: 'Tool-using chatbot'},
                {type: 'doc', id: 'guides/llm/projects/agent-on-a-sandbox-task/README', label: 'Agent on a sandbox task'},
                {type: 'doc', id: 'guides/llm/projects/swe-style-coding-agent/README', label: 'SWE-style coding agent'},
                {type: 'doc', id: 'guides/llm/projects/rl-fine-tune-for-tools/README', label: 'RL fine-tune for tools'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 8: Evaluation',
              items: [
                {type: 'doc', id: 'guides/llm/projects/mmlu-re-run/README', label: 'MMLU re-run'},
                {type: 'doc', id: 'guides/llm/projects/prompt-sensitivity-sweep/README', label: 'Prompt sensitivity sweep'},
                {type: 'doc', id: 'guides/llm/projects/contamination-probe/README', label: 'Contamination probe'},
                {type: 'doc', id: 'guides/llm/projects/llm-as-judge-pipeline/README', label: 'LLM-as-judge pipeline'},
                {type: 'doc', id: 'guides/llm/projects/capability-profile/README', label: 'Capability profile'},
                {type: 'doc', id: 'guides/llm/projects/custom-eval/README', label: 'Custom eval'},
                {type: 'doc', id: 'guides/llm/projects/arena-reproduction/README', label: 'Arena reproduction'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 9: Efficient Inference and Deployment',
              items: [
                {type: 'doc', id: 'guides/llm/projects/kv-cache-from-scratch/README', label: 'KV cache from scratch'},
                {type: 'doc', id: 'guides/llm/projects/quantize-a-7b-model/README', label: 'Quantize a 7B model'},
                {type: 'doc', id: 'guides/llm/projects/speculative-decoding/README', label: 'Speculative decoding'},
                {type: 'doc', id: 'guides/llm/projects/serve-with-vllm/README', label: 'Serve with vLLM'},
                {type: 'doc', id: 'guides/llm/projects/prefix-cache-study/README', label: 'Prefix-cache study'},
                {type: 'doc', id: 'guides/llm/projects/constrained-json-generation/README', label: 'Constrained JSON generation'},
                {type: 'doc', id: 'guides/llm/projects/distill-7b-1b/README', label: 'Distill 7B → 1B'},
                {type: 'doc', id: 'guides/llm/projects/fp8-serving/README', label: 'FP8 serving'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 10: Safety, Interpretability, and Frontier Topics',
              items: [
                {type: 'doc', id: 'guides/llm/projects/hallucination-triage/README', label: 'Hallucination triage'},
                {type: 'doc', id: 'guides/llm/projects/memorization-probe/README', label: 'Memorization probe'},
                {type: 'doc', id: 'guides/llm/projects/prompt-injection-red-team/README', label: 'Prompt-injection red team'},
                {type: 'doc', id: 'guides/llm/projects/gcg-jailbreak/README', label: 'GCG jailbreak'},
                {type: 'doc', id: 'guides/llm/projects/linear-probes-for-facts/README', label: 'Linear probes for facts'},
                {type: 'doc', id: 'guides/llm/projects/tiny-sae/README', label: 'Tiny SAE'},
                {type: 'doc', id: 'guides/llm/projects/rlaif-on-a-small-task/README', label: 'RLAIF on a small task'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Image Generation',
          link: {type: 'doc', id: 'guides/image-generation/README'},
          items: [
            {
              type: 'category',
              label: 'Phase 1: Foundations — Images, Likelihoods, and the Manifold Problem',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/manifold-visualizer/README', label: 'Manifold visualizer'},
                {type: 'doc', id: 'guides/image-generation/projects/bits-per-dim-baseline/README', label: 'Bits-per-dim baseline'},
                {type: 'doc', id: 'guides/image-generation/projects/tiny-pixelcnn/README', label: 'Tiny PixelCNN'},
                {type: 'doc', id: 'guides/image-generation/projects/fid-from-scratch/README', label: 'FID from scratch'},
                {type: 'doc', id: 'guides/image-generation/projects/real-nvp-toy/README', label: 'Real NVP toy'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 2: Autoencoders and VAEs',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/tiny-ae-on-mnist/README', label: 'Tiny AE on MNIST'},
                {type: 'doc', id: 'guides/image-generation/projects/vanilla-vae/README', label: 'Vanilla VAE'},
                {type: 'doc', id: 'guides/image-generation/projects/beta-vae-study/README', label: 'β-VAE study'},
                {type: 'doc', id: 'guides/image-generation/projects/conditional-vae/README', label: 'Conditional VAE'},
                {type: 'doc', id: 'guides/image-generation/projects/hierarchical-vae/README', label: 'Hierarchical VAE'},
                {type: 'doc', id: 'guides/image-generation/projects/latent-traversal/README', label: 'Latent traversal'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 3: Discrete Latents — VQ-VAE, VQ-GAN, and Modern Tokenizers',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/vq-vae-on-cifar-10/README', label: 'VQ-VAE on CIFAR-10'},
                {type: 'doc', id: 'guides/image-generation/projects/codebook-collapse-hunt/README', label: 'Codebook collapse hunt'},
                {type: 'doc', id: 'guides/image-generation/projects/vq-gan/README', label: 'VQ-GAN'},
                {type: 'doc', id: 'guides/image-generation/projects/fsq-tokenizer/README', label: 'FSQ tokenizer'},
                {type: 'doc', id: 'guides/image-generation/projects/tiny-image-transformer/README', label: 'Tiny image transformer'},
                {type: 'doc', id: 'guides/image-generation/projects/masked-token-model/README', label: 'Masked-token model'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 4: Generative Adversarial Networks',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/vanilla-gan-on-mnist/README', label: 'Vanilla GAN on MNIST'},
                {type: 'doc', id: 'guides/image-generation/projects/wgan-gp/README', label: 'WGAN-GP'},
                {type: 'doc', id: 'guides/image-generation/projects/conditional-gan/README', label: 'Conditional GAN'},
                {type: 'doc', id: 'guides/image-generation/projects/stylegan-tour/README', label: 'StyleGAN tour'},
                {type: 'doc', id: 'guides/image-generation/projects/gan-inversion/README', label: 'GAN inversion'},
                {type: 'doc', id: 'guides/image-generation/projects/fid-head-to-head/README', label: 'FID head-to-head'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 5: Diffusion Models — Foundations (DDPM)',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/ddpm-on-mnist/README', label: 'DDPM on MNIST'},
                {type: 'doc', id: 'guides/image-generation/projects/ddpm-on-cifar-10/README', label: 'DDPM on CIFAR-10'},
                {type: 'doc', id: 'guides/image-generation/projects/cosine-vs-linear-schedule/README', label: 'Cosine vs linear schedule'},
                {type: 'doc', id: 'guides/image-generation/projects/ddim-sampler/README', label: 'DDIM sampler'},
                {type: 'doc', id: 'guides/image-generation/projects/class-conditional-ddpm/README', label: 'Class-conditional DDPM'},
                {type: 'doc', id: 'guides/image-generation/projects/classifier-guidance/README', label: 'Classifier guidance'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 6: Score-Based, EDM, and Modern Diffusion Theory',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/score-matching-from-scratch/README', label: 'Score matching from scratch'},
                {type: 'doc', id: 'guides/image-generation/projects/higher-order-sampler/README', label: 'Higher-order sampler'},
                {type: 'doc', id: 'guides/image-generation/projects/classifier-free-guidance/README', label: 'Classifier-free guidance'},
                {type: 'doc', id: 'guides/image-generation/projects/edm-reparameterization/README', label: 'EDM reparameterization'},
                {type: 'doc', id: 'guides/image-generation/projects/probability-flow-ode/README', label: 'Probability flow ODE'},
                {type: 'doc', id: 'guides/image-generation/projects/vp-vs-ve-comparison/README', label: 'VP vs VE comparison'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 7: Latent Diffusion and Stable Diffusion',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/run-sd-inference/README', label: 'Run SD inference'},
                {type: 'doc', id: 'guides/image-generation/projects/img2img-and-inpainting/README', label: 'img2img and inpainting'},
                {type: 'doc', id: 'guides/image-generation/projects/train-a-latent-ddpm/README', label: 'Train a latent DDPM'},
                {type: 'doc', id: 'guides/image-generation/projects/train-a-vae-for-diffusion/README', label: 'Train a VAE for diffusion'},
                {type: 'doc', id: 'guides/image-generation/projects/negative-prompts-study/README', label: 'Negative prompts study'},
                {type: 'doc', id: 'guides/image-generation/projects/long-prompt-test/README', label: 'Long-prompt test'},
                {type: 'doc', id: 'guides/image-generation/projects/outpainting/README', label: 'Outpainting'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 8: Diffusion Transformers and Flow Matching',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/implement-dit-s-2/README', label: 'Implement DiT-S/2'},
                {type: 'doc', id: 'guides/image-generation/projects/44-2d-rope-for-dit/README', label: '2D RoPE for DiT'},
                {type: 'doc', id: 'guides/image-generation/projects/rectified-flow-from-scratch/README', label: 'Rectified flow from scratch'},
                {type: 'doc', id: 'guides/image-generation/projects/mmdit-block/README', label: 'MMDiT block'},
                {type: 'doc', id: 'guides/image-generation/projects/re-flow/README', label: 'Re-flow'},
                {type: 'doc', id: 'guides/image-generation/projects/compare-dit-and-u-net-scaling/README', label: 'Compare DiT and U-Net scaling'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 9: Conditioning, Control, and Personalization',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/lora-fine-tune/README', label: 'LoRA fine-tune'},
                {type: 'doc', id: 'guides/image-generation/projects/dreambooth/README', label: 'DreamBooth'},
                {type: 'doc', id: 'guides/image-generation/projects/textual-inversion/README', label: 'Textual Inversion'},
                {type: 'doc', id: 'guides/image-generation/projects/controlnet-from-scratch/README', label: 'ControlNet from scratch'},
                {type: 'doc', id: 'guides/image-generation/projects/instructpix2pix-style-data/README', label: 'InstructPix2Pix-style data'},
                {type: 'doc', id: 'guides/image-generation/projects/ddim-inversion-edit/README', label: 'DDIM inversion + edit'},
                {type: 'doc', id: 'guides/image-generation/projects/style-lora/README', label: 'Style LoRA'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 10: Training at Scale, Distillation, Evaluation, and Frontier Topics',
              items: [
                {type: 'doc', id: 'guides/image-generation/projects/mini-laion-pipeline/README', label: 'Mini LAION pipeline'},
                {type: 'doc', id: 'guides/image-generation/projects/caption-ablation/README', label: 'Caption ablation'},
                {type: 'doc', id: 'guides/image-generation/projects/aspect-ratio-bucketing/README', label: 'Aspect-ratio bucketing'},
                {type: 'doc', id: 'guides/image-generation/projects/consistency-distillation/README', label: 'Consistency distillation'},
                {type: 'doc', id: 'guides/image-generation/projects/adversarial-diffusion-distillation/README', label: 'Adversarial Diffusion Distillation'},
                {type: 'doc', id: 'guides/image-generation/projects/watermarking/README', label: 'Watermarking'},
                {type: 'doc', id: 'guides/image-generation/projects/geneval-run/README', label: 'GenEval run'},
                {type: 'doc', id: 'guides/image-generation/projects/human-correlated-eval/README', label: 'Human-correlated eval'},
                {type: 'doc', id: 'guides/image-generation/projects/text-rendering-probe/README', label: 'Text-rendering probe'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Reinforcement Learning',
          link: {type: 'doc', id: 'guides/reinforcement-learning/README'},
          items: [
            {
              type: 'category',
              label: 'Phase 1: MDPs and the Bellman Equations',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/build-a-gridworld/README', label: 'Build a gridworld'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/policy-evaluation-by-matrix-inverse/README', label: 'Policy evaluation by matrix inverse'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/hand-trace-bellman-backups/README', label: 'Hand-trace Bellman backups'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/discount-factor-study/README', label: 'Discount factor study'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/pomdp-exercise/README', label: 'POMDP exercise'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 2: Tabular Methods — DP, Monte Carlo, and TD',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/value-iteration-on-frozenlake/README', label: 'Value iteration on FrozenLake'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/policy-iteration-vs-value-iteration/README', label: 'Policy iteration vs value iteration'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/first-visit-mc/README', label: 'First-visit MC'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/q-learning-on-frozenlake/README', label: 'Q-learning on FrozenLake'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/sarsa-vs-q-learning-on-cliff-walking/README', label: 'SARSA vs Q-learning on Cliff Walking'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/eligibility-traces/README', label: 'Eligibility traces'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 3: Function Approximation and DQN',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/dqn-on-cartpole/README', label: 'DQN on CartPole'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/add-a-replay-buffer/README', label: 'Add a replay buffer'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/atari-pong/README', label: 'Atari Pong'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/double-dueling/README', label: 'Double + Dueling'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/prioritized-replay/README', label: 'Prioritized replay'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/mini-rainbow/README', label: 'Mini Rainbow'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/distributional-dqn-c51/README', label: 'Distributional DQN (C51)'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 4: Policy Gradients — REINFORCE to PPO',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/reinforce-on-cartpole/README', label: 'REINFORCE on CartPole'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/add-a-value-baseline/README', label: 'Add a value baseline'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/a2c-with-parallel-envs/README', label: 'A2C with parallel envs'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/ppo-from-scratch/README', label: 'PPO from scratch'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/the-37-details/README', label: 'The 37 details'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/ppo-on-atari/README', label: 'PPO on Atari'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/trpo-for-comparison/README', label: 'TRPO for comparison'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 5: Continuous Control — DDPG, TD3, SAC',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/ddpg-on-pendulum/README', label: 'DDPG on Pendulum'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/td3-on-halfcheetah/README', label: 'TD3 on HalfCheetah'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/sac-on-a-mujoco-suite/README', label: 'SAC on a Mujoco suite'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/automatic-temperature-tuning/README', label: 'Automatic temperature tuning'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/reparameterization-audit/README', label: 'Reparameterization audit'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/sample-efficiency-study/README', label: 'Sample efficiency study'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 6: Model-Based RL',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/pets-random-shooting-mpc/README', label: 'PETS / random shooting MPC'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/cem-mpc/README', label: 'CEM-MPC'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/mini-mbpo/README', label: 'Mini MBPO'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/dreamer-v3-reproduction/README', label: 'Dreamer V3 reproduction'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/mini-muzero/README', label: 'Mini MuZero'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/td-mpc2-study/README', label: 'TD-MPC2 study'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 7: Offline RL',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/bc-baseline-on-d4rl/README', label: 'BC baseline on D4RL'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/naive-q-learning-on-the-same-dataset/README', label: 'Naive Q-learning on the same dataset'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/implement-cql/README', label: 'Implement CQL'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/implement-iql/README', label: 'Implement IQL'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/decision-transformer/README', label: 'Decision Transformer'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/dataset-quality-study/README', label: 'Dataset-quality study'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 8: Exploration',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/epsilon-greedy-on-a-chain/README', label: 'ε-greedy on a chain'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/count-based-on-a-small-env/README', label: 'Count-based on a small env'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/rnd-on-atari/README', label: 'RND on Atari'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/icm/README', label: 'ICM'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/diayn/README', label: 'DIAYN'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/noisy-tv-experiment/README', label: 'Noisy-TV experiment'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 9: RL for Language Models — RLHF, DPO, GRPO, RLVR',
              items: [
                {type: 'doc', id: 'guides/reinforcement-learning/projects/sft-a-small-base-model/README', label: 'SFT a small base model'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/train-a-reward-model/README', label: 'Train a reward model'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/ppo-style-rlhf/README', label: 'PPO-style RLHF'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/dpo/README', label: 'DPO'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/grpo-from-scratch/README', label: 'GRPO from scratch'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/rlvr-on-math/README', label: 'RLVR on math'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/length-bias-audit/README', label: 'Length-bias audit'},
                {type: 'doc', id: 'guides/reinforcement-learning/projects/reward-hacking-demo/README', label: 'Reward hacking demo'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Video Generation',
          link: {type: 'doc', id: 'guides/video-generation/README'},
          items: [
            {
              type: 'category',
              label: 'Phase 1: Foundations — Video as a Tensor',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/video-loader-benchmark/README', label: 'Video loader benchmark'},
                {type: 'doc', id: 'guides/video-generation/projects/frame-extractor/README', label: 'Frame extractor'},
                {type: 'doc', id: 'guides/video-generation/projects/optical-flow-visualizer/README', label: 'Optical flow visualizer'},
                {type: 'doc', id: 'guides/video-generation/projects/scene-cut-detector/README', label: 'Scene-cut detector'},
                {type: 'doc', id: 'guides/video-generation/projects/storage-study/README', label: 'Storage study'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 2: Classical and Early Neural Video Generation',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/moving-mnist-predictor/README', label: 'Moving MNIST predictor'},
                {type: 'doc', id: 'guides/video-generation/projects/film-frame-interpolation/README', label: 'FILM frame interpolation'},
                {type: 'doc', id: 'guides/video-generation/projects/tiny-video-gan/README', label: 'Tiny video GAN'},
                {type: 'doc', id: 'guides/video-generation/projects/read-mocogan/README', label: 'Read MoCoGAN'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 3: Image-to-Video as a Stepping Stone',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/run-svd-inference/README', label: 'Run SVD inference'},
                {type: 'doc', id: 'guides/video-generation/projects/animatediff-tour/README', label: 'AnimateDiff tour'},
                {type: 'doc', id: 'guides/video-generation/projects/tiny-i2v-model/README', label: 'Tiny I2V model'},
                {type: 'doc', id: 'guides/video-generation/projects/motion-control/README', label: 'Motion control'},
                {type: 'doc', id: 'guides/video-generation/projects/camera-trajectory/README', label: 'Camera trajectory'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 4: Video Diffusion — The Modern Foundation',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/inflate-sd-to-a-video-model/README', label: 'Inflate SD to a video model'},
                {type: 'doc', id: 'guides/video-generation/projects/joint-image-video-training/README', label: 'Joint image-video training'},
                {type: 'doc', id: 'guides/video-generation/projects/temporal-cfg-study/README', label: 'Temporal CFG study'},
                {type: 'doc', id: 'guides/video-generation/projects/cascaded-super-resolution/README', label: 'Cascaded super-resolution'},
                {type: 'doc', id: 'guides/video-generation/projects/compare-attention-patterns/README', label: 'Compare attention patterns'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 5: Latent Video Diffusion and Video Tokenizers',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/frame-by-frame-2d-vae/README', label: 'Frame-by-frame 2D VAE'},
                {type: 'doc', id: 'guides/video-generation/projects/train-a-small-3d-vae/README', label: 'Train a small 3D VAE'},
                {type: 'doc', id: 'guides/video-generation/projects/causal-3d-vae/README', label: 'Causal 3D VAE'},
                {type: 'doc', id: 'guides/video-generation/projects/magvit-v2-style-tokenizer/README', label: 'MagViT-v2-style tokenizer'},
                {type: 'doc', id: 'guides/video-generation/projects/diffusion-on-latents/README', label: 'Diffusion on latents'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 6: Diffusion Transformers (DiT) and Sora-Class Models',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/implement-dit-for-video/README', label: 'Implement DiT for video'},
                {type: 'doc', id: 'guides/video-generation/projects/flow-matching-from-scratch/README', label: 'Flow matching from scratch'},
                {type: 'doc', id: 'guides/video-generation/projects/read-and-reproduce-opensora/README', label: 'Read and reproduce OpenSora'},
                {type: 'doc', id: 'guides/video-generation/projects/mmdit-for-video/README', label: 'MMDiT for video'},
                {type: 'doc', id: 'guides/video-generation/projects/variable-resolution/README', label: 'Variable resolution'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 7: Conditioning, Control, and Editing',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/long-prompt-handling/README', label: 'Long-prompt handling'},
                {type: 'doc', id: 'guides/video-generation/projects/controlnet-video/README', label: 'ControlNet-Video'},
                {type: 'doc', id: 'guides/video-generation/projects/talking-head/README', label: 'Talking head'},
                {type: 'doc', id: 'guides/video-generation/projects/video-inversion-edit/README', label: 'Video inversion + edit'},
                {type: 'doc', id: 'guides/video-generation/projects/lora-for-video/README', label: 'LoRA for video'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 8: Long-Form and Consistent Video',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/sliding-window-t2v/README', label: 'Sliding-window T2V'},
                {type: 'doc', id: 'guides/video-generation/projects/keyframe-interpolation/README', label: 'Keyframe interpolation'},
                {type: 'doc', id: 'guides/video-generation/projects/character-consistency/README', label: 'Character consistency'},
                {type: 'doc', id: 'guides/video-generation/projects/llm-shot-planner/README', label: 'LLM shot planner'},
                {type: 'doc', id: 'guides/video-generation/projects/streaming-t2v/README', label: 'Streaming T2V'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 9: World Models and Interactive Video',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/action-conditioned-video/README', label: 'Action-conditioned video'},
                {type: 'doc', id: 'guides/video-generation/projects/gamengen-reproduction-mini/README', label: 'GameNGen reproduction (mini)'},
                {type: 'doc', id: 'guides/video-generation/projects/latent-action-inference/README', label: 'Latent action inference'},
                {type: 'doc', id: 'guides/video-generation/projects/world-model-for-rl/README', label: 'World model for RL'},
                {type: 'doc', id: 'guides/video-generation/projects/real-time-latency-hunt/README', label: 'Real-time latency hunt'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 10: Training at Scale, Evaluation, and Frontier Topics',
              items: [
                {type: 'doc', id: 'guides/video-generation/projects/run-vbench-end-to-end/README', label: 'Run VBench end to end'},
                {type: 'doc', id: 'guides/video-generation/projects/recaption-a-dataset/README', label: 'Recaption a dataset'},
                {type: 'doc', id: 'guides/video-generation/projects/aspect-ratio-bucketing/README', label: 'Aspect-ratio bucketing'},
                {type: 'doc', id: 'guides/video-generation/projects/consistency-model-distillation/README', label: 'Consistency-model distillation'},
                {type: 'doc', id: 'guides/video-generation/projects/watermarking/README', label: 'Watermarking'},
                {type: 'doc', id: 'guides/video-generation/projects/physical-plausibility-probe/README', label: 'Physical-plausibility probe'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Robotics',
          link: {type: 'doc', id: 'guides/robotics/README'},
          items: [
            {
              type: 'category',
              label: 'Phase 1: Rigid-Body Transforms and Kinematics',
              items: [
                {type: 'doc', id: 'guides/robotics/projects/transform-calculator/README', label: 'Transform calculator'},
                {type: 'doc', id: 'guides/robotics/projects/urdf-visualizer/README', label: 'URDF visualizer'},
                {type: 'doc', id: 'guides/robotics/projects/forward-kinematics-from-scratch/README', label: 'Forward kinematics from scratch'},
                {type: 'doc', id: 'guides/robotics/projects/jacobian-from-scratch/README', label: 'Jacobian from scratch'},
                {type: 'doc', id: 'guides/robotics/projects/damped-least-squares-ik/README', label: 'Damped least-squares IK'},
                {type: 'doc', id: 'guides/robotics/projects/null-space-posture-control/README', label: 'Null-space posture control'},
                {type: 'doc', id: 'guides/robotics/projects/hand-eye-calibration/README', label: 'Hand-eye calibration'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 2: Dynamics and Classical Control',
              items: [
                {type: 'doc', id: 'guides/robotics/projects/pendulum-pid/README', label: 'Pendulum PID'},
                {type: 'doc', id: 'guides/robotics/projects/cart-pole-lqr/README', label: 'Cart-pole LQR'},
                {type: 'doc', id: 'guides/robotics/projects/inverse-dynamics-from-scratch/README', label: 'Inverse dynamics from scratch'},
                {type: 'doc', id: 'guides/robotics/projects/computed-torque-trajectory-tracking/README', label: 'Computed-torque trajectory tracking'},
                {type: 'doc', id: 'guides/robotics/projects/impedance-control/README', label: 'Impedance control'},
                {type: 'doc', id: 'guides/robotics/projects/mpc-for-a-unicycle/README', label: 'MPC for a unicycle'},
                {type: 'doc', id: 'guides/robotics/projects/real-arm-pid-tune/README', label: 'Real-arm PID tune'},
                {type: 'doc', id: 'guides/robotics/projects/force-controlled-drawing/README', label: 'Force-controlled drawing'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 3: Sensing and Perception',
              items: [
                {type: 'doc', id: 'guides/robotics/projects/camera-calibration/README', label: 'Camera calibration'},
                {type: 'doc', id: 'guides/robotics/projects/apriltag-pose/README', label: 'AprilTag pose'},
                {type: 'doc', id: 'guides/robotics/projects/stereo-depth/README', label: 'Stereo depth'},
                {type: 'doc', id: 'guides/robotics/projects/icp-registration/README', label: 'ICP registration'},
                {type: 'doc', id: 'guides/robotics/projects/visual-odometry/README', label: 'Visual odometry'},
                {type: 'doc', id: 'guides/robotics/projects/imu-integration/README', label: 'IMU integration'},
                {type: 'doc', id: 'guides/robotics/projects/object-6-dof-pose/README', label: 'Object 6-DoF pose'},
                {type: 'doc', id: 'guides/robotics/projects/open-vocab-grasping/README', label: 'Open-vocab grasping'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 4: State Estimation, Localization, and SLAM',
              items: [
                {type: 'doc', id: 'guides/robotics/projects/24-1d-kf/README', label: '1D KF'},
                {type: 'doc', id: 'guides/robotics/projects/25-2d-constant-velocity-tracker/README', label: '2D constant-velocity tracker'},
                {type: 'doc', id: 'guides/robotics/projects/ekf-localization/README', label: 'EKF localization'},
                {type: 'doc', id: 'guides/robotics/projects/particle-filter/README', label: 'Particle filter'},
                {type: 'doc', id: 'guides/robotics/projects/imu-integration/README', label: 'IMU dead reckoning'},
                {type: 'doc', id: 'guides/robotics/projects/vio-mvp/README', label: 'VIO MVP'},
                {type: 'doc', id: 'guides/robotics/projects/29-2d-lidar-slam/README', label: '2D LiDAR SLAM'},
                {type: 'doc', id: 'guides/robotics/projects/factor-graph-practice/README', label: 'Factor-graph practice'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Multimodal Learning',
          link: {type: 'doc', id: 'guides/multimodal-learning/README'},
          items: [
            {
              type: 'category',
              label: 'Phase 1: Foundations — What "Multimodal" Actually Means',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/modality-survey/README', label: 'Modality survey'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/visualize-the-modality-gap/README', label: 'Visualize the modality gap'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/toy-retrieval/README', label: 'Toy retrieval'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 2: Encoders for Each Modality',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/implement-vit-from-scratch/README', label: 'Implement ViT from scratch'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/compare-encoders/README', label: 'Compare encoders'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/mel-spectrogram-pipeline/README', label: 'Mel spectrogram pipeline'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/whisper-encoder-reuse/README', label: 'Whisper encoder reuse'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/patch-size-study/README', label: 'Patch-size study'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 3: Contrastive Learning — CLIP and Friends',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/implement-infonce/README', label: 'Implement InfoNCE'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/tiny-clip/README', label: 'Tiny CLIP'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/zero-shot-imagenet/README', label: 'Zero-shot ImageNet'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/hard-negative-mining/README', label: 'Hard-negative mining'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/temperature-ablation/README', label: 'Temperature ablation'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/data-filtering-with-clip/README', label: 'Data filtering with CLIP'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 4: Fusion Architectures — How Modalities Talk to Each Other',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/concat-vs-cross-attn/README', label: 'Concat vs cross-attn'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/implement-q-former/README', label: 'Implement Q-Former'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/adapter-for-a-new-modality/README', label: 'Adapter for a new modality'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/perceiver-io/README', label: 'Perceiver IO'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/gated-cross-attention/README', label: 'Gated cross-attention'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 5: Vision-Language Models (VLMs)',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/llava-from-scratch/README', label: 'LLaVA from scratch'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/visual-instruction-tuning/README', label: 'Visual instruction tuning'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/dynamic-resolution/README', label: 'Dynamic resolution'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/grounding-head/README', label: 'Grounding head'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/compare-projectors/README', label: 'Compare projectors'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/inference-optimization/README', label: 'Inference optimization'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 6: Audio, Speech, and Video',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/mel-spectrogram-from-scratch/README', label: 'Mel spectrogram from scratch'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/whisper-fine-tune/README', label: 'Whisper fine-tune'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/encodec-tour/README', label: 'EnCodec tour'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/speech-llm/README', label: 'Speech LLM'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/video-frame-vlm/README', label: 'Video frame VLM'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/native-video-model/README', label: 'Native video model'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 7: Unified and Any-to-Any Models',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/discrete-image-tokens/README', label: 'Discrete image tokens'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/tiny-chameleon/README', label: 'Tiny Chameleon'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/modality-balancing/README', label: 'Modality balancing'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/moe-for-multimodal/README', label: 'MoE for multimodal'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/reverse-direction/README', label: 'Reverse direction'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 8: Training at Scale — Data, Compute, and Alignment',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/mini-laion-pipeline/README', label: 'Mini LAION pipeline'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/caption-ablation/README', label: 'Caption ablation'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/modality-ratio-sweep/README', label: 'Modality ratio sweep'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/multimodal-dpo/README', label: 'Multimodal DPO'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/hallucination-eval/README', label: 'Hallucination eval'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 9: Evaluation and Benchmarks',
              items: [
                {type: 'doc', id: 'guides/multimodal-learning/projects/run-a-vlm-evaluation-harness/README', label: 'Run a VLM evaluation harness'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/reproduce-a-leaderboard-result/README', label: 'Reproduce a leaderboard result'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/benchmark-contamination-check/README', label: 'Benchmark contamination check'},
                {type: 'doc', id: 'guides/multimodal-learning/projects/human-correlated-eval/README', label: 'Human-correlated eval'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Inference Systems',
          link: {type: 'doc', id: 'guides/inference-systems/README'},
          items: [
            {
              type: 'category',
              label: 'Phase 1: The Anatomy of an Inference Request',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/manual-inference-loop/README', label: 'Manual inference loop'},
                {type: 'doc', id: 'guides/inference-systems/projects/streaming-server/README', label: 'Streaming server'},
                {type: 'doc', id: 'guides/inference-systems/projects/stop-string-matcher/README', label: 'Stop-string matcher'},
                {type: 'doc', id: 'guides/inference-systems/projects/sampling-kernel/README', label: 'Sampling kernel'},
                {type: 'doc', id: 'guides/inference-systems/projects/detokenizer-fuzzer/README', label: 'Detokenizer fuzzer'},
                {type: 'doc', id: 'guides/inference-systems/projects/determinism-audit/README', label: 'Determinism audit'},
                {type: 'doc', id: 'guides/inference-systems/projects/request-lifecycle-tracer/README', label: 'Request-lifecycle tracer'},
                {type: 'doc', id: 'guides/inference-systems/projects/diffusion-vs-llm-serving/README', label: 'Diffusion vs LLM serving'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 2: The KV Cache',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/kv-cache-from-scratch/README', label: 'KV cache from scratch'},
                {type: 'doc', id: 'guides/inference-systems/projects/kv-size-calculator/README', label: 'KV size calculator'},
                {type: 'doc', id: 'guides/inference-systems/projects/tiny-paged-cache/README', label: 'Tiny paged cache'},
                {type: 'doc', id: 'guides/inference-systems/projects/prefix-share-benchmark/README', label: 'Prefix-share benchmark'},
                {type: 'doc', id: 'guides/inference-systems/projects/kv-quantization-study/README', label: 'KV-quantization study'},
                {type: 'doc', id: 'guides/inference-systems/projects/attention-sink-eviction/README', label: 'Attention-sink eviction'},
                {type: 'doc', id: 'guides/inference-systems/projects/cpu-nvme-offload/README', label: 'CPU/NVMe offload'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 3: Batching and Scheduling',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/static-vs-continuous/README', label: 'Static vs. continuous'},
                {type: 'doc', id: 'guides/inference-systems/projects/padding-waste-audit/README', label: 'Padding waste audit'},
                {type: 'doc', id: 'guides/inference-systems/projects/chunked-prefill-simulator/README', label: 'Chunked prefill simulator'},
                {type: 'doc', id: 'guides/inference-systems/projects/disaggregated-poc/README', label: 'Disaggregated PoC'},
                {type: 'doc', id: 'guides/inference-systems/projects/priority-queue/README', label: 'Priority queue'},
                {type: 'doc', id: 'guides/inference-systems/projects/cache-aware-admission/README', label: 'Cache-aware admission'},
                {type: 'doc', id: 'guides/inference-systems/projects/slo-aware-scheduler/README', label: 'SLO-aware scheduler'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 4: Speculative Decoding',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/greedy-speculative-decoding/README', label: 'Greedy speculative decoding'},
                {type: 'doc', id: 'guides/inference-systems/projects/sampling-mode-rejection/README', label: 'Sampling-mode rejection'},
                {type: 'doc', id: 'guides/inference-systems/projects/n-gram-lookup/README', label: 'N-gram lookup'},
                {type: 'doc', id: 'guides/inference-systems/projects/tune-k/README', label: 'Tune `k`'},
                {type: 'doc', id: 'guides/inference-systems/projects/medusa-heads/README', label: 'Medusa heads'},
                {type: 'doc', id: 'guides/inference-systems/projects/speculation-batching/README', label: 'Speculation + batching'},
                {type: 'doc', id: 'guides/inference-systems/projects/workload-sensitivity/README', label: 'Workload sensitivity'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 5: Serving-Time Quantization Decisions',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/quantize-a-7b-model-end-to-end/README', label: 'Quantize a 7B model end-to-end'},
                {type: 'doc', id: 'guides/inference-systems/projects/fp8-kv-cache/README', label: 'FP8 KV cache'},
                {type: 'doc', id: 'guides/inference-systems/projects/w4a8-ablation/README', label: 'W4A8 ablation'},
                {type: 'doc', id: 'guides/inference-systems/projects/mixed-precision-deployment/README', label: 'Mixed-precision deployment'},
                {type: 'doc', id: 'guides/inference-systems/projects/calibration-drift-study/README', label: 'Calibration drift study'},
                {type: 'doc', id: 'guides/inference-systems/projects/eval-suite-for-quantized-models/README', label: 'Eval-suite for quantized models'},
                {type: 'doc', id: 'guides/inference-systems/projects/fp4-blackwell-deployment/README', label: 'FP4 (Blackwell) deployment'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 6: Inference-Relevant Kernels and Hardware Choices',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/roofline-plot-for-your-engine/README', label: 'Roofline plot for *your* engine'},
                {type: 'doc', id: 'guides/inference-systems/projects/profile-a-single-decode-step/README', label: 'Profile a single decode step'},
                {type: 'doc', id: 'guides/inference-systems/projects/flashdecoding-ablation/README', label: 'FlashDecoding ablation'},
                {type: 'doc', id: 'guides/inference-systems/projects/skinny-m-kernel-study/README', label: 'Skinny-M kernel study'},
                {type: 'doc', id: 'guides/inference-systems/projects/cuda-graphs-for-decode/README', label: 'CUDA Graphs for decode'},
                {type: 'doc', id: 'guides/inference-systems/projects/stream-overlap-audit/README', label: 'Stream-overlap audit'},
                {type: 'doc', id: 'guides/inference-systems/projects/hardware-comparison/README', label: 'Hardware comparison'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 7: Distributed and Disaggregated Serving',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/tp-2-from-scratch/README', label: 'TP=2 from scratch'},
                {type: 'doc', id: 'guides/inference-systems/projects/vllm-multi-replica/README', label: 'vLLM multi-replica'},
                {type: 'doc', id: 'guides/inference-systems/projects/prefix-aware-routing/README', label: 'Prefix-aware routing'},
                {type: 'doc', id: 'guides/inference-systems/projects/disaggregated-prototype/README', label: 'Disaggregated prototype'},
                {type: 'doc', id: 'guides/inference-systems/projects/failure-mode-drill/README', label: 'Failure-mode drill'},
                {type: 'doc', id: 'guides/inference-systems/projects/session-affinity-routing/README', label: 'Session-affinity routing'},
                {type: 'doc', id: 'guides/inference-systems/projects/cross-region-latency/README', label: 'Cross-region latency'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 8: Long Context, Structured Output, and Multi-Tenant Tricks',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/needle-in-a-haystack/README', label: 'Needle-in-a-haystack'},
                {type: 'doc', id: 'guides/inference-systems/projects/prefix-kv-caching/README', label: 'Prefix KV caching'},
                {type: 'doc', id: 'guides/inference-systems/projects/json-mode-reliability/README', label: 'JSON-mode reliability'},
                {type: 'doc', id: 'guides/inference-systems/projects/custom-grammar/README', label: 'Custom grammar'},
                {type: 'doc', id: 'guides/inference-systems/projects/multi-lora-serving/README', label: 'Multi-LoRA serving'},
                {type: 'doc', id: 'guides/inference-systems/projects/speculation-json-mode/README', label: 'Speculation + JSON-mode'},
                {type: 'doc', id: 'guides/inference-systems/projects/stateful-session-api/README', label: 'Stateful session API'},
                {type: 'doc', id: 'guides/inference-systems/projects/ring-attention-from-scratch/README', label: 'Ring attention from scratch'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 9: Observability, SLOs, and Cost Economics',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/metric-instrumentation/README', label: 'Metric instrumentation'},
                {type: 'doc', id: 'guides/inference-systems/projects/synthetic-load-tests/README', label: 'Synthetic load tests'},
                {type: 'doc', id: 'guides/inference-systems/projects/slo-simulation/README', label: 'SLO simulation'},
                {type: 'doc', id: 'guides/inference-systems/projects/error-budget-tracker/README', label: 'Error budget tracker'},
                {type: 'doc', id: 'guides/inference-systems/projects/cost-report/README', label: 'Cost report'},
                {type: 'doc', id: 'guides/inference-systems/projects/right-sizing-experiment/README', label: 'Right-sizing experiment'},
                {type: 'doc', id: 'guides/inference-systems/projects/load-shedding-policy/README', label: 'Load-shedding policy'},
                {type: 'doc', id: 'guides/inference-systems/projects/postmortem-drill/README', label: 'Postmortem drill'},
              ],
            },
            {
              type: 'category',
              label: 'Phase 10: Frontier Topics in Serving',
              items: [
                {type: 'doc', id: 'guides/inference-systems/projects/reasoning-model-serving/README', label: 'Reasoning-model serving'},
                {type: 'doc', id: 'guides/inference-systems/projects/stateful-sessions/README', label: 'Stateful sessions'},
                {type: 'doc', id: 'guides/inference-systems/projects/router-model/README', label: 'Router model'},
                {type: 'doc', id: 'guides/inference-systems/projects/moe-serving/README', label: 'MoE serving'},
                {type: 'doc', id: 'guides/inference-systems/projects/fp4-blackwell-inference/README', label: 'FP4 (Blackwell) inference'},
                {type: 'doc', id: 'guides/inference-systems/projects/on-device-build/README', label: 'On-device build'},
                {type: 'doc', id: 'guides/inference-systems/projects/speculative-agent-steps/README', label: 'Speculative agent steps'},
              ],
            },
          ],
        },
        {type: 'doc', id: 'guides/ai-hardware/README', label: 'AI Hardware'},
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        {type: 'doc', id: 'shared/glossary', label: 'Glossary'},
      ],
    },
  ],
};

module.exports = sidebars;
